import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Locale } from "@/i18n.config";
import { ThemeProvider } from "@/components/theme-provider";

const montserrat = Montserrat({
  subsets: ["latin"],
});

// const roboto = Roboto({
//   weight : ['100' , '300' , '400' , '500' , '700' , '900'],
//   subsets: ["greek"],

// })

// const poppins = Poppins({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
//   subsets: ["latin-ext"],
// });
export const metadata: Metadata = {
  title: "In Talks",
  description: "Generated by create next app",
};

interface PropsType {
  params: Promise<{ lang: Locale }>; 
  children: React.ReactNode;
}

export default async function RootLayout({
  children,
  params,
}: PropsType) { 
  const { lang } = await params; 


  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={`${montserrat.className} dark:bg-bgDarkColor`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
